# Generated by Django 4.0.6 on 2023-04-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Doctor', 'Dr'), ('Professor Doctor', 'Prof.Dr'), ('Doctor der Naturwissenschaft', 'Dr.rer.nat')], max_length=50),
        ),
    ]
