# Generated by Django 4.0.6 on 2023-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_doctor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Prof.Dr', 'Prof.Dr'), ('Dr.rer.nat', 'Dr.rer.nat')], max_length=50),
        ),
    ]
