# Generated by Django 4.0.6 on 2023-04-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_doctor_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='creator',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='creator',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
